"""End-to-end package checks with disposable installs; no compiler is built."""

from contextlib import contextmanager
from dataclasses import replace
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tarfile
import threading
import zipfile

import pytest

from test_hlsl_cli import checkout, cli, files, workspace

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from hlsl_cli.command import Request, preview, run  # noqa: E402
from hlsl_cli.lit_relocation import LitRelocationError, relocate_lit  # noqa: E402


def make_install(root, kind="llvm", platform="native"):
    llvm = checkout(root, "llvm-project", "llvm")
    offload = checkout(root, "offload-test-suite", "offload")
    golden = checkout(root, "offload-golden-images", "golden")
    build = (llvm if kind == "llvm" else offload) / (
        "build" + ("." + platform if platform != "native" else "")
    )
    prefix = build / "install"
    (prefix / "bin").mkdir(parents=True)
    if kind == "llvm":
        (prefix / "bin/clang").write_text("compiler")
        (prefix / "bin/clang-dxc").write_text("compiler")
    (prefix / ("bin/offloader.exe" if platform.startswith("windows-")
               else "bin/offloader")).write_text("offloader")
    if kind == "llvm":
        (prefix / "lib/clang/1/include").mkdir(parents=True)
        (prefix / "lib/clang/1/include/hlsl.h").write_text("HLSL")
    (prefix / "share/hlsl-test-suite/test").mkdir(parents=True)
    (prefix / "share/hlsl-test-suite/test/lit.cfg.py").write_text("# suite\n")
    (prefix / "share/hlsl-test-suite/golden-images").mkdir(parents=True)
    (prefix / "share/hlsl-test-suite/golden-images/ref.png").write_bytes(b"PNG")
    (llvm / "llvm/utils/lit/lit").mkdir(parents=True)
    (llvm / "llvm/utils/lit/lit/__init__.py").write_text("# fixture\n")
    (llvm / "llvm/utils/lit/lit/main.py").write_text("def main(): pass\n")
    test_root = build / ("tools/OffloadTest/test" if kind == "llvm" else "test")
    site = test_root / "clang-vk/lit.site.cfg.py"
    site.parent.mkdir(parents=True)
    dist_build = "build" + ("." + platform if platform != "native" else "")
    bin_dir = build / "bin" if kind == "llvm" else llvm / dist_build / "install/bin"
    dxc = root / "host-dxc/bin"
    dxc.mkdir(parents=True)
    site.write_text(
        f"# Autogenerated from {offload / 'test/lit.site.cfg.py.in'}\n"
        "import os\n"
        "def path(value):\n"
        "    return os.path.normpath(os.path.join(os.path.dirname(__file__), value))\n"
        f'config.offloadtest_obj_root = path(r"{test_root.parent}")\n'
        f'config.offloadtest_src_root = path(r"{offload}")\n'
        f'config.offloadtest_tools_dir = path(r"{build / "bin"}")\n'
        f'config.llvm_tools_dir = path(r"{bin_dir}")\n'
        f'config.offloadtest_dxc = path(r"{dxc / "dxc"}")\n'
        f'config.offloadtest_dxc_dir = r"{dxc}"\n'
        f'config.goldenimage_dir = r"{golden}"\n'
        'config.offloadtest_os = "Windows"\n'
        "\nimport lit.llvm\n"
        "lit.llvm.initialize(lit_config, config)\n"
        'lit_config.load_config(config, os.path.join(config.offloadtest_src_root, "test/lit.cfg.py"))\n'
    )
    if kind == "offload":
        dist = llvm / dist_build / "install"
        (dist / "bin").mkdir(parents=True)
        executable = ".exe" if platform.startswith("windows-") else ""
        (dist / f"bin/clang{executable}").write_text("clang")
        (dist / f"bin/clang-dxc{executable}").write_text("compiler")
        (dist / f"bin/FileCheck{executable}").write_text("filecheck")
        (dist / f"bin/split-file{executable}").write_text("split-file")
        (dist / "lib/clang/1/include").mkdir(parents=True)
        (dist / "lib/clang/1/include/hlsl.h").write_text("HLSL")
    return llvm, offload, golden, build, site


def unpack(path, target):
    target.mkdir()
    if path.suffix == ".zip":
        with zipfile.ZipFile(path) as archive:
            archive.extractall(target)
            return archive.namelist()
    with tarfile.open(path, "r:gz") as archive:
        archive.extractall(target, filter="data")
        return archive.getnames()


@pytest.mark.parametrize("kind", ["llvm", "offload"])
def test_full_archive_from_installed_layouts(workspace, kind, tmp_path):
    llvm, offload, golden, build, site = make_install(workspace, kind)
    selected = llvm if kind == "llvm" else offload
    archive = tmp_path / "full.tar.gz"
    result = cli(workspace, "package", "full", "--in", str(selected), "--out", str(archive), "--no-auto")
    assert result.returncode == 0, result.stderr
    assert archive.is_file()
    names = unpack(archive, tmp_path / "moved")
    assert "test/clang-vk/lit.site.cfg.py" in names
    moved = tmp_path / "moved"
    assert (moved / "bin/lit").is_file()
    assert (moved / "share/hlsl-test-suite/lit/lit/main.py").is_file()
    assert (moved / "share/hlsl-test-suite/python/yaml/__init__.py").is_file()
    assert (moved / "share/hlsl-test-suite/golden-images/ref.png").read_bytes() == b"PNG"
    assert (moved / "bin/clang-dxc").is_file()
    assert (moved / "lib/clang/1/include/hlsl.h").read_text() == "HLSL"
    if kind == "offload":
        assert (moved / "bin/clang").read_text() == "clang"
        assert (moved / "bin/FileCheck").read_text() == "filecheck"
        assert (moved / "bin/split-file").read_text() == "split-file"
        assert (moved / "bin/offloader").read_text() == "offloader"
    config = (moved / "test/clang-vk/lit.site.cfg.py").read_text()
    for machine_path in (str(workspace), str(build), str(site)):
        assert machine_path not in config
    provenance = json.loads((moved / "provenance.json").read_text())
    assert provenance["suites"] == ["clang-vk"]
    assert provenance["sources"]["llvm-project"]["revision"]
    assert "target_python" in provenance
    assert "dxc" in provenance


def test_relocated_lit_site_loads_after_moving_archive(workspace, tmp_path):
    llvm, offload, golden, build, _ = make_install(workspace)
    archive = tmp_path / "full.tar.gz"
    assert cli(workspace, "package", "full", "--in", str(llvm),
               "--out", str(archive)).returncode == 0
    moved = tmp_path / "elsewhere"
    unpack(archive, moved)
    script = r'''
import json, os, runpy, sys
from pathlib import Path
from types import SimpleNamespace
site = Path(sys.argv[1])
sys.path.insert(0, str(site.parents[2] / "share/hlsl-test-suite/lit"))
class Lit:
    maxIndividualTestTime = 0
    def note(self, message): pass
    def load_config(self, config, source):
        assert Path(source).is_file()
config = SimpleNamespace()
lit_config = Lit()
runpy.run_path(str(site), init_globals={"config": config, "lit_config": lit_config})
print(json.dumps({"source": config.offloadtest_src_root,
                  "tools": config.llvm_tools_dir,
                  "golden": config.goldenimage_dir,
                  "dxc": config.offloadtest_dxc_dir}))
'''
    # Supply the import expected by a configured site; no real compiler or lit
    # installation is needed to validate the relocated paths at runtime.
    lit = moved / "share/hlsl-test-suite/lit/lit"
    (lit / "LitConfig.py").write_text("class LitConfig: pass\n")
    (lit / "llvm.py").write_text("def initialize(lit_config, config): pass\n")
    target_dxc = tmp_path / "another-machine/dxc/bin"
    target_dxc.mkdir(parents=True)
    result = subprocess.run(
        [sys.executable, "-c", script, str(moved / "test/clang-vk/lit.site.cfg.py")],
        env={**os.environ, "HLSL_DXC_DIR": str(target_dxc),
             "PYTHONDONTWRITEBYTECODE": "1"},
        capture_output=True, text=True,
    )
    assert result.returncode == 0, result.stderr
    resolved = json.loads(result.stdout)
    assert resolved["source"] == str(moved / "share/hlsl-test-suite")
    assert resolved["golden"] == str(moved / "share/hlsl-test-suite/golden-images")
    assert resolved["tools"] == str(moved / "bin")
    assert resolved["dxc"] == str(target_dxc)


def test_only_configured_runnable_suites_are_archived(workspace, tmp_path):
    llvm, _, _, build, site = make_install(workspace)
    test_root = site.parent.parent
    other = test_root / "vk/lit.site.cfg.py"
    other.parent.mkdir()
    other.write_text(site.read_text().replace('clang-vk', 'vk'))
    unit = test_root / "Unit/lit.site.cfg.py"
    unit.parent.mkdir()
    unit.write_text(site.read_text())
    lavapipe = test_root / "vk-lavapipe/lit.site.cfg.py"
    lavapipe.parent.mkdir()
    lavapipe.write_text(site.read_text())
    planned = cli(workspace, "package", "full", "--in", str(llvm), "--dry-run")
    assert "configured suites" in planned.stdout
    assert "clang-vk, vk" in planned.stdout
    archive = tmp_path / "full.tar.gz"
    result = cli(workspace, "package", "full", "--in", str(llvm),
                 "--out", str(archive))
    assert result.returncode == 0, result.stderr
    names = unpack(archive, tmp_path / "selected")
    assert "test/vk/lit.site.cfg.py" in names
    assert "test/Unit/lit.site.cfg.py" not in names
    assert "test/vk-lavapipe/lit.site.cfg.py" not in names
    assert json.loads((tmp_path / "selected/provenance.json").read_text())[
        "suites"
    ] == ["clang-vk", "vk"]


def test_linux_arm64_full_package_marks_target_execution_unverified(workspace, tmp_path):
    llvm, _, _, _, _ = make_install(workspace, platform="linux-arm64")
    archive = tmp_path / "full.tar.gz"
    args = ("package", "full", "--in", str(llvm), "--platform", "linux-arm64",
            "--out", str(archive))
    preview = cli(workspace, *args, "--dry-run")
    assert preview.returncode == 0, preview.stderr
    assert "Target execution unverified" not in preview.stdout
    result = cli(workspace, *args)
    assert result.returncode == 0, result.stderr
    unpack(archive, tmp_path / "linux-arm64")
    stage = tmp_path / "linux-arm64"
    assert "Target execution unverified (linux-arm64)" in (
        stage / "README.txt").read_text()
    provenance = json.loads((stage / "provenance.json").read_text())
    assert provenance["target_execution_unverified"] is True


def test_windows_archive_materializes_links(workspace, tmp_path):
    llvm, _, _, build, _ = make_install(workspace, "llvm", "windows-x64")
    (build / "install/bin/clang-dxc.exe").symlink_to("clang.exe")
    (build / "install/bin/clang.exe").write_bytes(b"MZ")
    archive = tmp_path / "full.zip"
    result = cli(workspace, "package", "full", "--in", str(llvm),
                 "--platform", "windows-x64", "--out", str(archive))
    assert result.returncode == 0, result.stderr
    assert "Target execution unverified" not in result.stdout
    unpack(archive, tmp_path / "unpacked")
    assert (tmp_path / "unpacked/bin/clang-dxc.exe").read_bytes() == b"MZ"
    assert json.loads((tmp_path / "unpacked/provenance.json").read_text())[
        "target_execution_unverified"
    ]


def test_windows_rejects_links_hidden_inside_directory_alias(workspace, tmp_path):
    llvm, _, _, build, _ = make_install(workspace, "llvm", "windows-x64")
    directory = build / "install/share/hlsl-test-suite/nested"
    directory.mkdir()
    (directory / "secret").symlink_to(tmp_path / "host-secret")
    (tmp_path / "host-secret").write_text("must never enter archive")
    (directory.parent / "alias").symlink_to("nested", target_is_directory=True)
    archive = tmp_path / "full.zip"
    result = cli(workspace, "package", "full", "--in", str(llvm),
                 "--platform", "windows-x64", "--out", str(archive))
    assert result.returncode != 0
    assert "symlink escapes" in result.stderr
    assert not archive.exists()


def test_preview_does_not_write_or_install(workspace, tmp_path):
    llvm, _, _, build, _ = make_install(workspace)
    archive = tmp_path / "planned.tar.gz"
    before = files(workspace)
    report = cli(workspace, "package", "full", "--in", str(llvm),
                 "--out", str(archive), "--dry-run")
    assert report.returncode == 0, report.stderr
    assert str(archive) in report.stdout
    assert files(workspace) == before
    assert not archive.exists()
    assert not (workspace / ".hlsl-dev").exists()
    (build / "install").rename(build / "saved-install")
    report = cli(workspace, "package", "full", "--in", str(llvm),
                 "--out", str(archive), "--dry-run")
    assert report.returncode == 0, report.stderr
    assert "prerequisite: build" in report.stdout
    assert not (build / "install").exists()
    assert not archive.exists()
    assert "cost: LLVM/offload install" in report.stdout


def test_relocator_rejects_unmapped_and_surviving_literals_before_writing(workspace, tmp_path):
    llvm, _, _, _, site = make_install(workspace)
    stage = tmp_path / "stage"
    target = stage / "test/clang-vk/lit.site.cfg.py"
    mappings = {llvm: "share/llvm"}
    with pytest.raises(LitRelocationError, match="unmapped"):
        relocate_lit(site.read_text(), site, target, stage, mappings)
    assert not target.exists()
    body = site.read_text() + f'\nconfig.extra = "{workspace / "secret"}"\n'
    mappings.update({workspace / "offload-test-suite": "share/hlsl-test-suite",
                     workspace / "offload-golden-images": "share/hlsl-test-suite/golden-images",
                     workspace / "host-dxc/bin": "dxc/bin",
                     llvm / "build/bin": "bin"})
    with pytest.raises(LitRelocationError, match="absolute paths survive"):
        relocate_lit(body, site, target, stage, mappings)
    embedded = site.read_text() + f'\nconfig.flag = "--driver={workspace / "driver"}"\n'
    with pytest.raises(LitRelocationError, match="absolute paths survive"):
        relocate_lit(embedded, site, target, stage, mappings)
    commented = site.read_text() + f'\n# build host {workspace / "driver"}\n'
    with pytest.raises(LitRelocationError, match="absolute paths survive"):
        relocate_lit(commented, site, target, stage, mappings)
    assert not target.exists()


def test_untrusted_symlink_and_missing_install_leave_output_untouched(workspace, tmp_path):
    llvm, _, _, build, _ = make_install(workspace)
    archive = tmp_path / "full.tar.gz"
    archive.write_bytes(b"previous")
    (build / "install/bin/escape").symlink_to(tmp_path / "private")
    (tmp_path / "private").write_text("host secret")
    result = cli(workspace, "package", "full", "--in", str(llvm),
                 "--out", str(archive))
    assert result.returncode != 0
    assert "symlink escapes" in result.stderr
    assert archive.read_bytes() == b"previous"
    (build / "install/bin/escape").unlink()
    (build / "install/bin/offloader").unlink()
    no_auto = cli(workspace, "package", "full", "--in", str(llvm),
                  "--out", str(archive), "--no-auto")
    assert no_auto.returncode != 0
    assert "--no-auto" in no_auto.stderr
    assert archive.read_bytes() == b"previous"


def test_missing_suite_and_host_path_do_not_replace_archive(workspace, tmp_path):
    llvm, _, _, _, site = make_install(workspace)
    archive = tmp_path / "full.tar.gz"
    archive.write_bytes(b"old archive")
    site.write_text(site.read_text() + f'\nconfig.other = "{workspace / "host-only"}"\n')
    bad = cli(workspace, "package", "full", "--in", str(llvm), "--out", str(archive))
    assert bad.returncode != 0
    assert "absolute paths survive" in bad.stderr
    assert archive.read_bytes() == b"old archive"
    site.unlink()
    absent = cli(workspace, "package", "full", "--in", str(llvm), "--out", str(archive))
    assert absent.returncode != 0
    assert "no configured" in absent.stderr
    assert archive.read_bytes() == b"old archive"


def test_standalone_windows_merges_both_installs_without_host_paths(workspace, tmp_path):
    llvm, offload, _, build, site = make_install(
        workspace, "offload", "windows-x64"
    )
    suite = build / "install/share/hlsl-test-suite"
    (suite / "test/Feature").mkdir()
    (suite / "test/Feature/example.test").write_text("# RUN: offloader\n")
    (suite / "golden-images/ref.png").write_bytes(b"PNG")
    (build / "install/bin/D3D12").mkdir()
    (build / "install/bin/D3D12/D3D12Core.dll").write_bytes(b"D3D12")
    (build / "install/bin/offloader.exe").rename(
        build / "install/bin/offloader-real.exe"
    )
    (build / "install/bin/offloader.exe").symlink_to("offloader-real.exe")
    # An old copy in the offload prefix must not replace the compiler's headers.
    (build / "install/lib/clang/1/include").mkdir(parents=True)
    (build / "install/lib/clang/1/include/hlsl.h").write_text("stale")
    dist = llvm / "build.windows-x64/install"
    (dist / "bin/clang-dxc.exe").unlink()
    (dist / "bin/clang.exe").write_bytes(b"MZ")
    (dist / "bin/clang-dxc.exe").symlink_to("clang.exe")
    (dist / "bin/FileCheck.exe").rename(dist / "bin/FileCheck-real.exe")
    (dist / "bin/FileCheck.exe").symlink_to("FileCheck-real.exe")
    (dist / "bin/tools").mkdir()
    (dist / "bin/tools/extra.exe").write_bytes(b"extra")
    (dist / "bin/tool-alias").symlink_to("tools", target_is_directory=True)
    (dist / "lib/clang/1/include/hlsl/hlsl_detail.h").parent.mkdir()
    (dist / "lib/clang/1/include/hlsl/hlsl_detail.h").write_text("resource")

    archive = tmp_path / "standalone.zip"
    before = files(workspace)
    preview = cli(workspace, "package", "full", "--in", str(offload),
                  "--platform", "windows-x64", "--out", str(archive),
                  "--no-auto", "--dry-run")
    assert preview.returncode == 0, preview.stderr
    assert f"LLVM distribution {dist}" in preview.stdout
    assert "Target execution unverified" not in preview.stdout
    assert files(workspace) == before
    assert not archive.exists()
    result = cli(workspace, "package", "full", "--in", str(offload),
                 "--platform", "windows-x64", "--out", str(archive), "--no-auto")
    assert result.returncode == 0, result.stderr
    assert "Target execution unverified" not in result.stdout
    with zipfile.ZipFile(archive) as zipped:
        assert all((entry.external_attr >> 16) & 0o170000 != 0o120000
                   for entry in zipped.infolist())
    names = unpack(archive, tmp_path / "portable")
    moved = tmp_path / "portable"
    assert "test/clang-vk/lit.site.cfg.py" in names
    assert (moved / "bin/clang-dxc.exe").read_bytes() == b"MZ"
    assert (moved / "bin/FileCheck.exe").read_text() == "filecheck"
    assert (moved / "bin/split-file.exe").read_text() == "split-file"
    assert (moved / "bin/offloader.exe").read_text() == "offloader"
    assert (moved / "bin/tool-alias/extra.exe").read_bytes() == b"extra"
    assert (moved / "bin/D3D12/D3D12Core.dll").read_bytes() == b"D3D12"
    assert (moved / "lib/clang/1/include/hlsl.h").read_text() == "HLSL"
    assert (moved / "lib/clang/1/include/hlsl/hlsl_detail.h").read_text() == "resource"
    assert (moved / "share/hlsl-test-suite/test/Feature/example.test").is_file()
    assert (moved / "share/hlsl-test-suite/golden-images/ref.png").read_bytes() == b"PNG"
    assert (moved / "share/hlsl-test-suite/lit/lit/main.py").is_file()
    assert (moved / "share/hlsl-test-suite/python/yaml/__init__.py").is_file()
    assert (moved / "bin/lit.cmd").is_file()
    assert all(str(workspace).encode() not in path.read_bytes()
               for path in moved.rglob("*") if path.is_file())
    assert "Target execution unverified (windows-x64)" in (moved / "README.txt").read_text()
    assert json.loads((moved / "provenance.json").read_text())[
        "target_execution_unverified"
    ] is True
    assert not any(p.is_symlink() for p in moved.rglob("*"))


def test_standalone_build_and_package_lock_prefix_before_build(workspace, monkeypatch):
    from hlsl_cli import offload, package

    llvm, tree, _, build, _ = make_install(workspace, "offload")
    prefix = llvm / "build/install"
    (prefix / "lib/cmake/llvm").mkdir(parents=True)
    (prefix / "lib/cmake/llvm/LLVMConfig.cmake").touch()
    dxc = workspace / "host-dxc/bin"
    (dxc / "dxc").touch()
    (dxc / "dxv").touch()
    monkeypatch.setenv("HLSL_CMAKE_FLAGS_OFFLOAD", "-G Ninja -DLLVM_DIR=$HD_LLVM_CMAKE_DIR")
    monkeypatch.setenv("HLSL_LOCK_TIMEOUT", "1")
    building = threading.Event()
    package_trying_prefix = threading.Event()
    package_has_prefix = threading.Event()
    offload_has_prefix = threading.Event()
    events = []
    errors = []
    real_offload_lock = offload.build_lock
    real_package_lock = package.build_lock

    @contextmanager
    def offload_lock(root, directory):
        with real_offload_lock(root, directory):
            if directory == prefix:
                offload_has_prefix.set()
            if directory == build:
                building.set()
                # On the old build-first order, allow package to acquire the
                # prefix and expose the opposing nested lock acquisition.
                if not offload_has_prefix.is_set():
                    assert package_has_prefix.wait(2)
            yield

    @contextmanager
    def package_lock(root, directory):
        if directory == prefix:
            package_trying_prefix.set()
        with real_package_lock(root, directory):
            if directory == prefix:
                package_has_prefix.set()
            yield

    def fake_command(argv, directory, *, env=None):
        events.append("build")
        assert package_trying_prefix.wait(2)
        assert not package_has_prefix.is_set()
        if "-B" in argv:
            directory.mkdir(exist_ok=True)
            (directory / "build.ninja").touch()

    def fake_stage(plan, stage):
        events.append("stage")
        (stage / "contents").write_text("packaged")
        return ["contents"]

    def fake_archive(stage, target):
        target.write_text((stage / "contents").read_text())

    monkeypatch.setattr(offload, "build_lock", offload_lock)
    monkeypatch.setattr(package, "build_lock", package_lock)
    monkeypatch.setattr(offload, "_run_command", fake_command)
    monkeypatch.setattr(package, "_stage", fake_stage)
    monkeypatch.setattr(package, "_archive", fake_archive)
    build_request = Request("build", workspace, worktree=str(tree), dxc=str(dxc),
                            targets=("install-offload-tools",))
    archive = workspace / "full.tar.gz"
    package_request = Request("package full", workspace, worktree=str(tree),
                              out=str(archive), no_auto=True)

    def run_action(action, request):
        try:
            action(request)
        except Exception as error:
            errors.append(error)

    worker = threading.Thread(target=run_action, args=(offload.execute, build_request),
                              daemon=True)
    packer = threading.Thread(target=run_action, args=(package.execute, package_request),
                              daemon=True)
    worker.start()
    assert building.wait(2)
    packer.start()
    worker.join(4)
    packer.join(4)
    assert not worker.is_alive() and not packer.is_alive(), "build/package hung"
    assert not errors, errors
    assert events == ["build", "build", "stage"]
    assert archive.read_text() == "packaged"


def test_offload_replans_selected_distribution_before_build(workspace, monkeypatch):
    from hlsl_cli import offload

    llvm, tree, _, _, _ = make_install(workspace, "offload")
    prefix = llvm / "build/install"
    (prefix / "lib/cmake/llvm").mkdir(parents=True)
    (prefix / "lib/cmake/llvm/LLVMConfig.cmake").touch()
    dxc = workspace / "host-dxc/bin"
    (dxc / "dxc").touch()
    (dxc / "dxv").touch()
    monkeypatch.setenv("HLSL_CMAKE_FLAGS_OFFLOAD", "-G Ninja -DLLVM_DIR=$HD_LLVM_CMAKE_DIR")
    request = Request("build", workspace, worktree=str(tree), dxc=str(dxc))
    initial = offload.plan(request)
    changed = replace(initial, selections={
        **initial.selections,
        "configured": {**initial.selections["configured"],
                       "dist_prefix": str(workspace / "other-dist")},
    })
    plans = iter((initial, changed))
    monkeypatch.setattr(offload, "plan", lambda _: next(plans))
    monkeypatch.setattr(offload, "_run_command", lambda *args, **kwargs:
                        pytest.fail("stale selection executed"))
    with pytest.raises(offload.BuildError, match="selection changed"):
        offload.execute(request)


def test_standalone_external_distribution_and_missing_prefix(workspace, tmp_path):
    llvm, offload, _, build, site = make_install(workspace, "offload")
    external = tmp_path / "external-dist"
    (external / "bin").mkdir(parents=True)
    (external / "bin/clang-dxc").write_text("selected compiler")
    (external / "bin/FileCheck").write_text("selected tool")
    (external / "lib/clang/1/include").mkdir(parents=True)
    (external / "lib/clang/1/include/hlsl.h").write_text("selected header")
    # This build was configured against the selected external prefix.
    site.write_text(site.read_text().replace(
        str(llvm / "build/install/bin"), str(external / "bin")
    ))
    archive = tmp_path / "external.tar.gz"
    archive.write_bytes(b"previous archive")
    missing = cli(workspace, "package", "full", "--in", str(offload),
                  "--dist-prefix", str(tmp_path / "missing"),
                  "--out", str(archive), "--no-auto")
    assert missing.returncode != 0
    assert "--no-auto" in missing.stderr
    assert archive.read_bytes() == b"previous archive"
    result = cli(workspace, "package", "full", "--in", str(offload),
                 "--dist-prefix", str(external), "--out", str(archive), "--no-auto")
    assert result.returncode == 0, result.stderr
    unpack(archive, tmp_path / "relocated")
    moved = tmp_path / "relocated"
    assert (moved / "bin/clang-dxc").read_text() == "selected compiler"
    assert (moved / "bin/FileCheck").read_text() == "selected tool"
    assert (moved / "lib/clang/1/include/hlsl.h").read_text() == "selected header"
    assert (moved / "bin/offloader").read_text() == "offloader"
    assert all(str(workspace).encode() not in path.read_bytes()
               for path in moved.rglob("*") if path.is_file())
    assert not (build / "install/bin/clang-dxc").exists()
    assert (llvm / "build/install/bin/clang-dxc").is_file()


def test_standalone_windows_rejects_distribution_host_symlink(workspace, tmp_path):
    llvm, offload, _, _, _ = make_install(workspace, "offload", "windows-x64")
    dist_bin = llvm / "build.windows-x64/install/bin"
    (dist_bin / "host-only.exe").symlink_to(tmp_path / "host-only.exe")
    (tmp_path / "host-only.exe").write_text("not for target")
    archive = tmp_path / "full.zip"
    archive.write_bytes(b"previous archive")
    result = cli(workspace, "package", "full", "--in", str(offload),
                 "--platform", "windows-x64", "--out", str(archive), "--no-auto")
    assert result.returncode != 0
    assert "symlink escapes" in result.stderr
    assert archive.read_bytes() == b"previous archive"


def make_dxc_build(root, platform="native"):
    dxc = checkout(root, "DirectXShaderCompiler", "dxc")
    build = dxc / ("build" + ("." + platform if platform != "native" else ""))
    (build / "bin").mkdir(parents=True)
    (build / "lib").mkdir()
    if platform.startswith("windows-"):
        for name in ("dxc.exe", "dxv.exe", "dxcompiler.dll", "dxil.dll"):
            (build / "bin" / name).write_bytes(b"MZ" + name.encode())
        (build / "lib/dxcompiler.lib").write_bytes(b"import")
    else:
        (build / "bin/dxc-3.7").write_bytes(b"compiler")
        (build / "bin/dxc").symlink_to("dxc-3.7")
        (build / "bin/dxv").write_bytes(b"validator")
        (build / "lib/libdxcompiler.so.3").write_bytes(b"library")
        (build / "lib/libdxcompiler.so").symlink_to("libdxcompiler.so.3")
    return dxc, build


def test_dxc_native_archive_is_curated_and_has_no_dangling_links(workspace, tmp_path):
    dxc, build = make_dxc_build(workspace)
    (build / "include").mkdir()
    (build / "include/hlsl.h").write_text("never ship headers")
    (build / "bin/clang").write_text("never ship clang")
    archive = tmp_path / "dxc.tar.gz"
    result = cli(workspace, "package", "dxc", "--in", str(dxc),
                 "--out", str(archive), "--no-auto")
    assert result.returncode == 0, result.stderr
    names = unpack(archive, tmp_path / "unpacked")
    assert set(names) == {
        "bin", "bin/dxc", "bin/dxv", "lib", "lib/libdxcompiler.so",
        "provenance.json",
    }
    unpacked = tmp_path / "unpacked"
    assert (unpacked / "bin/dxc").read_bytes() == b"compiler"
    assert (unpacked / "lib/libdxcompiler.so").read_bytes() == b"library"
    assert not list(unpacked.rglob("*.h"))
    assert not any(p.is_symlink() for p in unpacked.rglob("*"))
    assert json.loads((unpacked / "provenance.json").read_text())[
        "sources"
    ]["DirectXShaderCompiler"]["revision"]


def test_linux_arm64_dxc_package_marks_target_execution_unverified(workspace, tmp_path):
    dxc, _ = make_dxc_build(workspace, "linux-arm64")
    archive = tmp_path / "dxc.tar.gz"
    args = ("package", "dxc", "--in", str(dxc), "--platform", "linux-arm64",
            "--out", str(archive), "--no-auto")
    preview = cli(workspace, *args, "--dry-run")
    assert preview.returncode == 0, preview.stderr
    assert "Target execution unverified" not in preview.stdout
    result = cli(workspace, *args)
    assert result.returncode == 0, result.stderr
    unpack(archive, tmp_path / "linux-dxc")
    assert json.loads((tmp_path / "linux-dxc/provenance.json").read_text())[
        "target_execution_unverified"
    ] is True


def test_dxc_windows_archive_optional_libraries_and_unverified(workspace, tmp_path):
    dxc, build = make_dxc_build(workspace, "windows-x64")
    (build / "bin/dxil.dll").unlink()
    (build / "lib/dxcompiler.lib").unlink()
    (build / "bin/dxc.pdb").write_bytes(b"symbols")
    (build / "bin/dxc.exe").rename(build / "bin/dxc-real.exe")
    (build / "bin/dxc.exe").symlink_to("dxc-real.exe")
    archive = tmp_path / "dxc.zip"
    result = cli(workspace, "package", "dxc", "--platform", "windows-x64",
                 "--in", str(dxc), "--out", str(archive), "--no-auto")
    assert result.returncode == 0, result.stderr
    assert "Target execution unverified" not in result.stdout
    assert "dxil.dll" in result.stdout
    names = unpack(archive, tmp_path / "unpacked")
    assert set(names) == {
        "bin/dxc.exe", "bin/dxv.exe", "bin/dxcompiler.dll",
        "bin/dxc.pdb", "provenance.json",
    }
    assert (tmp_path / "unpacked/bin/dxc.exe").read_bytes() == b"MZdxc.exe"
    assert json.loads((tmp_path / "unpacked/provenance.json").read_text())[
        "target_execution_unverified"
    ] is True


def test_dxc_dry_run_is_read_only_even_without_binaries(workspace, tmp_path):
    dxc = checkout(workspace, "DirectXShaderCompiler", "dxc")
    archive = tmp_path / "planned.tar.gz"
    before = files(workspace)
    result = cli(workspace, "package", "dxc", "--in", str(dxc),
                 "--out", str(archive), "--dry-run")
    assert result.returncode == 0, result.stderr
    assert "prerequisite: build" in result.stdout
    assert str(archive) in result.stdout
    assert files(workspace) == before
    assert not archive.exists()
    blocked = cli(workspace, "package", "dxc", "--in", str(dxc), "--no-auto")
    assert blocked.returncode != 0
    assert "--no-auto" in blocked.stderr
    assert not (workspace / ".hlsl-dev").exists()


def test_dxc_invalid_symlink_and_missing_validator_preserve_archive(workspace, tmp_path):
    dxc, build = make_dxc_build(workspace)
    archive = tmp_path / "existing.tar.gz"
    archive.write_bytes(b"old archive")
    (build / "bin/dxc").unlink()
    (build / "bin/dxc").symlink_to(tmp_path / "host-only")
    (tmp_path / "host-only").write_text("secret")
    failed = cli(workspace, "package", "dxc", "--in", str(dxc),
                 "--out", str(archive), "--no-auto")
    assert failed.returncode != 0
    assert archive.read_bytes() == b"old archive"
    (build / "bin/dxc").unlink()
    (build / "bin/dxc").write_bytes(b"compiler")
    (build / "bin/dxv").unlink()
    missing = cli(workspace, "package", "dxc", "--in", str(dxc),
                  "--out", str(archive), "--no-auto")
    assert missing.returncode != 0
    assert "--no-auto" in missing.stderr
    assert archive.read_bytes() == b"old archive"


def test_dxc_windows_complete_archive_inspection_and_preview(workspace, tmp_path):
    dxc, build = make_dxc_build(workspace, "windows-arm64")
    (build / "lib/dxil.lib").write_bytes(b"signing import")
    (build / "bin/dxv.pdb").write_bytes(b"validator symbols")
    (build / "include").mkdir()
    (build / "include/hlsl.h").write_text("collision")
    archive = tmp_path / "windows.zip"
    before = files(workspace)
    dry = cli(workspace, "package", "dxc", "--in", str(dxc),
              "--platform", "windows-arm64", "--out", str(archive), "--dry-run")
    assert dry.returncode == 0, dry.stderr
    assert "Target execution unverified" not in dry.stdout
    assert "cost: stage and archive" in dry.stdout
    assert files(workspace) == before
    assert not archive.exists()
    result = cli(workspace, "package", "dxc", "--in", str(dxc),
                 "--platform", "windows-arm64", "--out", str(archive),
                 "--no-auto")
    assert result.returncode == 0, result.stderr
    names = unpack(archive, tmp_path / "relocated")
    assert set(names) == {
        "bin/dxc.exe", "bin/dxv.exe", "bin/dxcompiler.dll", "bin/dxil.dll",
        "bin/dxv.pdb", "lib/dxcompiler.lib", "lib/dxil.lib", "provenance.json",
    }
    assert (tmp_path / "relocated/lib/dxil.lib").read_bytes() == b"signing import"
    assert not (tmp_path / "relocated/include").exists()


def test_dxc_optional_escaping_link_cannot_replace_archive(workspace, tmp_path):
    dxc, build = make_dxc_build(workspace)
    archive = tmp_path / "prior.tar.gz"
    archive.write_bytes(b"prior archive")
    (build / "lib/libdxil.so").symlink_to(tmp_path / "secret")
    (tmp_path / "secret").write_text("do not package")
    result = cli(workspace, "package", "dxc", "--in", str(dxc),
                 "--out", str(archive), "--no-auto")
    assert result.returncode != 0
    assert "symlink escapes" in result.stderr
    assert archive.read_bytes() == b"prior archive"


@pytest.mark.parametrize("platform,suffix", [("native", ".tar.gz"),
                                             ("windows-x64", ".zip")])
def test_compiler_archive_prunes_prior_full_install(workspace, tmp_path, platform, suffix):
    llvm, _, _, build, _ = make_install(workspace, platform=platform)
    prefix = build / "install"
    for name in ("offloader", "api-query", "imgdiff"):
        (prefix / "bin" / (name + (".exe" if platform != "native" else ""))).write_text("offload")
    (prefix / "bin/D3D12").mkdir()
    (prefix / "bin/D3D12/SDK.dll").write_text("offload")
    (prefix / "bin/FileCheck").write_text("tool")
    if platform != "native":
        (prefix / "bin/clang.exe").write_bytes(b"MZ")
        (prefix / "bin/clang-dxc.exe").symlink_to("clang.exe")
        (prefix / "bin/clang-cl.exe").write_bytes(b"MZ")
    archive = tmp_path / ("compiler" + suffix)
    result = cli(workspace, "package", "compiler", "--in", str(llvm),
                 "--platform", platform, "--out", str(archive), "--no-auto")
    assert result.returncode == 0, result.stderr
    assert "Target execution unverified" not in result.stdout
    names = unpack(archive, tmp_path / "compiler")
    assert "bin/FileCheck" in names
    assert "lib/clang/1/include/hlsl.h" in names
    assert "bin/lit" in names
    assert "share/llvm/lit/lit/main.py" in names
    assert "share/llvm/python/yaml/__init__.py" in names
    assert not any("hlsl-test-suite" in name or name.startswith("test/")
                   or name.startswith("bin/D3D12/") for name in names)
    assert not any(name in names for name in (
        "bin/offloader", "bin/offloader.exe", "bin/api-query", "bin/api-query.exe",
        "bin/imgdiff", "bin/imgdiff.exe", "bin/clang-cl.exe"))
    if platform != "native":
        assert (tmp_path / "compiler/bin/clang-dxc.exe").read_bytes() == b"MZ"
    provenance = json.loads((tmp_path / "compiler/provenance.json").read_text())
    assert provenance["target_execution_unverified"] == (platform != "native")
    assert provenance["contents"] == "LLVM compiler and lit (no offload test suite)"
    # Never delete suite files from the shared install prefix.
    assert (prefix / "share/hlsl-test-suite/test/lit.cfg.py").is_file()
    assert (prefix / "bin/D3D12/SDK.dll").is_file()


def test_linux_arm64_compiler_package_marks_target_execution_unverified(workspace, tmp_path):
    llvm, _, _, _, _ = make_install(workspace, platform="linux-arm64")
    archive = tmp_path / "compiler.tar.gz"
    args = ("package", "compiler", "--in", str(llvm),
            "--platform", "linux-arm64", "--out", str(archive), "--no-auto")
    preview = cli(workspace, *args, "--dry-run")
    assert preview.returncode == 0, preview.stderr
    assert "Target execution unverified" not in preview.stdout
    result = cli(workspace, *args)
    assert result.returncode == 0, result.stderr
    unpack(archive, tmp_path / "linux-compiler")
    assert json.loads((tmp_path / "linux-compiler/provenance.json").read_text())[
        "target_execution_unverified"
    ] is True


def test_compiler_preview_is_read_only_and_does_not_need_offload(workspace, tmp_path):
    llvm, offload, golden, build, _ = make_install(workspace)
    # A compiler-only package must not require suite checkout or configured sites.
    import shutil
    shutil.rmtree(offload)
    shutil.rmtree(golden)
    shutil.rmtree(build / "tools")
    archive = tmp_path / "compiler.tar.gz"
    before = files(workspace)
    args = ("package", "compiler", "--in", str(llvm), "--out", str(archive))
    report = cli(workspace, *args, "--dry-run")
    assert report.returncode == 0, report.stderr
    assert "compiler" in report.stdout and "cost: stage and archive" in report.stdout
    assert files(workspace) == before
    assert not archive.exists()
    result = cli(workspace, *args, "--no-auto")
    assert result.returncode == 0, result.stderr
    assert archive.is_file()
    (build / "install").rename(build / "saved-install")
    before = files(workspace)
    preview = cli(workspace, *args, "--dry-run")
    assert preview.returncode == 0, preview.stderr
    assert "prerequisite: build install-distribution" in preview.stdout
    assert files(workspace) == before
    missing = cli(workspace, *args, "--no-auto")
    assert missing.returncode != 0
    assert "--no-auto" in missing.stderr


def test_cross_repro_missing_install_points_to_cli_installs(workspace):
    llvm, _, _, build, _ = make_install(workspace, platform="windows-x64")
    (build / "install").rename(build / "saved-install")
    before = files(workspace)
    report = cli(workspace, "package", "repro", "Graphics/MultipleViewports.test",
                 "--suite", "warp-d3d12", "--in", str(llvm),
                 "--platform", "windows-x64", "--dry-run")
    assert report.returncode != 0
    assert (f"hlsl distribution install --in {llvm} --platform windows-x64"
            in report.stderr)
    assert ("hlsl build install-offload-tools install-offload-test-suite"
            in report.stderr)
    assert files(workspace) == before


def test_compiler_rejects_non_llvm_and_invalid_cross_without_writes(workspace, tmp_path):
    llvm, offload, _, _, _ = make_install(workspace)
    before = files(workspace)
    wrong = cli(workspace, "package", "compiler", "--in", str(offload), "--dry-run")
    assert wrong.returncode != 0 and "LLVM" in wrong.stderr
    cross = cli(workspace, "package", "compiler", "--in", str(llvm),
                "--platform", "windows-x64", "--dry-run")
    assert cross.returncode == 0, cross.stderr
    assert "Target execution unverified" not in cross.stdout
    assert "prerequisite: build install-distribution" in cross.stdout
    assert files(workspace) == before
    not_installed = cli(workspace, "package", "compiler", "--in", str(llvm),
                        "--platform", "windows-x64")
    assert not_installed.returncode != 0
    assert "cross install missing" in not_installed.stderr
    assert not (workspace / ".hlsl-dev").exists()


def precompiled_fixture(workspace, platform="native"):
    llvm, offload, _, build, site = make_install(workspace, "llvm", platform)
    # Keep the native host compiler separate from the target install so a
    # missing host tool can be tested without invalidating the full package.
    native = llvm / "build/install/bin"
    native.mkdir(parents=True, exist_ok=True)
    split = native / "split-file"
    split.write_text(
        "#!/usr/bin/env python3\nimport pathlib,sys\n"
        "out=pathlib.Path(sys.argv[2]); out.mkdir(parents=True,exist_ok=True)\n"
        "(out/'source.hlsl').write_text('source')\n"
        "(out/'reject.hlsl').write_text('reject')\n"
    )
    compiler = native / "clang-dxc"
    compiler.write_text(
        "#!/usr/bin/env python3\nimport pathlib,sys\n"
        "a=sys.argv[1:]; out=next(a[i+1] for i,x in enumerate(a) if x=='-Fo')\n"
        "pathlib.Path(out).write_text('object')\n"
        "if 'reject' in a[-1]:\n print('validator rejected'); sys.exit(7)\n"
        "print('compiled')\n"
    )
    split.chmod(0o755)
    compiler.chmod(0o755)
    tests = build / "install/share/hlsl-test-suite/test/Feature"
    tests.mkdir(parents=True)
    for name, shader in (("good.test", "source.hlsl"),
                         ("bad.yaml", "reject.hlsl"),
                         ("inside.test", "source.hlsl")):
        output = "%t/inside.o" if name == "inside.test" else "%t.o"
        (tests / name).write_text(
            f"# RUN: split-file %s %t\n"
            f"# RUN: %dxc_target -T cs_6_5 -Fo {output} %t/{shader}\n"
            "# RUN: %offloader %t/pipeline.yaml %t.o\n"
        )
    (tests / "only-runtime.test").write_text("# RUN: %offloader %s\n")
    return llvm, build, native


def test_precompiled_archive_replays_host_verdicts_without_dxc(workspace, tmp_path):
    llvm, build, _ = precompiled_fixture(workspace)
    archive = tmp_path / "precompiled.tar.gz"
    before = files(workspace)
    dry = cli(workspace, "package", "precompiled", "clang-vk", "--in", str(llvm),
              "--no-auto", "--out", str(archive), "--dry-run")
    assert dry.returncode == 0, dry.stderr
    assert "native DXC (not selected)" in dry.stdout
    assert files(workspace) == before
    assert not archive.exists()
    result = cli(workspace, "package", "precompiled", "clang-vk", "--in", str(llvm),
                 "--no-auto", "--out", str(archive))
    assert result.returncode == 0, result.stderr
    unpack(archive, tmp_path / "moved")
    stage = tmp_path / "moved"
    assert not (stage / "bin/clang-dxc").exists()
    assert not (stage / "lib/clang").exists()
    assert not (stage / "dxc").exists()
    assert (stage / "bin/offloader").exists()
    assert (stage / "bin/lit").exists()
    data = json.loads((stage / "test/clang-vk/precompiled.json").read_text())
    key = "Feature/Output/bad.yaml.tmp.o"
    assert data["objects"][key] == {"status": 7, "output": "validator rejected\n"}
    assert not (stage / "test/clang-vk" / key).exists()
    assert "Feature/inside.test" in data["skipped"]
    assert "Feature/only-runtime.test" in data["skipped"]
    assert (stage / "test/clang-vk/Feature/Output/good.test.tmp.o").read_text() == "object"
    replay = stage / "bin/precompiled-cc.py"
    for name, status, message in (("good.test", 0, "compiled"),
                                  ("bad.yaml", 7, "rejected"),
                                  ("missing.test", 2, "PRECOMPILED.md")):
        output = stage / "test/clang-vk/Feature/Output" / (name + ".tmp.o")
        verdict = subprocess.run([sys.executable, str(replay), "-Fo", str(output)],
                                 capture_output=True, text=True)
        assert verdict.returncode == status
        assert message in verdict.stderr
    assert "Target execution unverified" not in (stage / "PRECOMPILED.md").read_text()
    site = (stage / "test/clang-vk/lit.site.cfg.py").read_text()
    assert "precompiled-cc.py" in site
    assert "config.substitutions" in site
    assert str(workspace) not in site


def test_precompiled_archive_runs_with_real_lit_and_no_target_compiler(workspace, tmp_path):
    llvm, build, native = precompiled_fixture(workspace)
    lit_source = Path(__file__).resolve().parents[2] / "llvm-project/llvm/utils/lit/lit"
    assert (lit_source / "main.py").is_file()
    lit_checkout = llvm / "llvm/utils/lit/lit"
    shutil.rmtree(lit_checkout)
    shutil.copytree(lit_source, lit_checkout,
                    ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))

    installed = build / "install"
    tests = installed / "share/hlsl-test-suite/test"
    (tests / "lit.cfg.py").write_text(
        "import os\n"
        "import lit.formats\n"
        "config.name = 'Precompiled-clang-vk'\n"
        "config.test_format = lit.formats.ShTest()\n"
        "config.suffixes = ['.test', '.yaml']\n"
        "config.excludes = ['Inputs', 'Output']\n"
        "config.test_source_root = os.path.dirname(__file__)\n"
        "config.test_exec_root = os.path.join(config.offloadtest_obj_root, 'test', 'clang-vk')\n"
        "config.substitutions.append(('%offloader', "
        "os.path.join(config.offloadtest_tools_dir, 'offloader')))\n"
        "config.substitutions.append(('split-file', "
        "os.path.join(config.llvm_tools_dir, 'split-file')))\n"
    )
    (tests / "Feature/inside.test").unlink()
    (tests / "Feature/only-runtime.test").unlink()
    (tests / "Feature/expected-bad.test").write_text(
        "# XFAIL: *\n"
        "# RUN: split-file %s %t\n"
        "# RUN: %dxc_target -T cs_6_5 -Fo %t.o %t/reject.hlsl\n"
        "# RUN: %offloader %t/pipeline.yaml %t.o\n"
    )
    offloader = installed / "bin/offloader"
    offloader.write_text(
        f"#!{sys.executable}\n"
        "import pathlib, sys\n"
        "sys.exit(0 if pathlib.Path(sys.argv[-1]).read_text() == 'object' else 1)\n"
    )
    offloader.chmod(0o755)

    archive = tmp_path / "precompiled.tar.gz"
    result = cli(workspace, "package", "precompiled", "clang-vk", "--in", str(llvm),
                 "--no-auto", "--out", str(archive))
    assert result.returncode == 0, result.stderr
    target = tmp_path / "target"
    unpack(archive, target)
    assert not (target / "bin/clang-dxc").exists()
    assert not (target / "dxc").exists()
    assert (target / "share/hlsl-test-suite/lit/lit/TestRunner.py").is_file()
    run_lit = subprocess.run(
        [str(target / "bin/lit"), "-v", str(target / "test/clang-vk")],
        cwd=target, capture_output=True, text=True,
        env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1",
             "PYTHON": sys.executable, "PATH": "/usr/bin:/bin"},
    )
    assert run_lit.returncode == 1, run_lit.stdout + run_lit.stderr
    assert "PASS: Precompiled-clang-vk :: Feature/good.test" in run_lit.stdout
    assert "FAIL: Precompiled-clang-vk :: Feature/bad.yaml" in run_lit.stdout
    assert "XFAIL: Precompiled-clang-vk :: Feature/expected-bad.test" in run_lit.stdout
    assert "Passed           : 1" in run_lit.stdout
    assert "Expectedly Failed: 1" in run_lit.stdout
    assert "Failed           : 1" in run_lit.stdout


def test_linux_arm64_precompiled_and_repro_mark_execution_unverified(workspace, tmp_path):
    llvm, _, _ = precompiled_fixture(workspace, "linux-arm64")
    for action, extra in (("precompiled", ("clang-vk",)),
                          ("repro", ("Feature/good.test", "--suite", "clang-vk"))):
        archive = tmp_path / f"{action}.tar.gz"
        args = ("package", action, *extra, "--in", str(llvm),
                "--platform", "linux-arm64", "--no-auto", "--out", str(archive))
        preview = cli(workspace, *args, "--dry-run")
        assert preview.returncode == 0, preview.stderr
        assert "Target execution unverified" not in preview.stdout
        result = cli(workspace, *args)
        assert result.returncode == 0, result.stderr
        stage = tmp_path / action
        unpack(archive, stage)
        instructions = "PRECOMPILED.md" if action == "precompiled" else "REPRO.md"
        assert "Target execution unverified (linux-arm64)" in (
            stage / instructions).read_text()
        assert json.loads((stage / "provenance.json").read_text())[
            "target_execution_unverified"
        ] is True


def test_linux_arm64_lit_fallback_marks_execution_unverified(workspace, tmp_path):
    llvm, build, _ = precompiled_fixture(workspace, "linux-arm64")
    (build / "install/bin/split-file").write_text("target split-file")
    tests = build / "install/share/hlsl-test-suite/test/Feature"
    (tests / "pipe.test").write_text(
        "# RUN: split-file %s %t\n"
        "# RUN: %dxc_target -Fo %t.o %t/source.hlsl\n"
        "# RUN: %offloader %t/pipeline.yaml %t.o | FileCheck %s\n"
    )
    archive = tmp_path / "fallback.tar.gz"
    args = ("package", "repro", "Feature/pipe.test", "--suite", "clang-vk",
            "--in", str(llvm), "--platform", "linux-arm64", "--no-auto",
            "--out", str(archive))
    result = cli(workspace, *args)
    assert result.returncode == 0, result.stderr
    assert "Target execution unverified" not in result.stdout
    stage = tmp_path / "fallback"
    unpack(archive, stage)
    assert "Target execution unverified (linux-arm64)" in (
        stage / "REPRO.md").read_text()
    assert json.loads((stage / "provenance.json").read_text())[
        "target_execution_unverified"
    ] is True


def test_precompiled_windows_is_unverified_and_does_not_ship_compiler(workspace, tmp_path):
    llvm, _, _ = precompiled_fixture(workspace, "windows-x64")
    archive = tmp_path / "precompiled.zip"
    result = cli(workspace, "package", "precompiled", "clang-vk", "--in", str(llvm),
                 "--platform", "windows-x64", "--no-auto", "--out", str(archive))
    assert result.returncode == 0, result.stderr
    assert "Target execution unverified" not in result.stdout
    unpack(archive, tmp_path / "windows")
    stage = tmp_path / "windows"
    assert not (stage / "bin/clang-dxc").exists()
    assert not (stage / "lib/clang").exists()
    assert (stage / "test/clang-vk/precompiled.json").exists()
    assert "Target execution unverified (windows-x64)" in (stage / "PRECOMPILED.md").read_text()
    assert not any(p.is_symlink() for p in stage.rglob("*"))


def test_precompiled_missing_native_compiler_does_not_replace_archive(workspace, tmp_path):
    llvm, _, native = precompiled_fixture(workspace)
    (native / "clang-dxc").unlink()
    archive = tmp_path / "precompiled.tar.gz"
    archive.write_bytes(b"old")
    result = cli(workspace, "package", "precompiled", "clang-vk", "--in", str(llvm),
                 "--no-auto", "--out", str(archive))
    assert result.returncode != 0
    assert "missing full install" in result.stderr
    assert archive.read_bytes() == b"old"


def test_repro_runs_every_named_test_without_target_python(workspace, tmp_path):
    llvm, build, native = precompiled_fixture(workspace)
    split = native / "split-file"
    split.write_text(split.read_text() +
                     "(out/'pipeline.yaml').write_text('pipeline')\n")
    tests = build / "install/share/hlsl-test-suite/test/Feature"
    (tests / "expected.test").write_text(
        "# XFAIL: *\n# RUN: split-file %s %t\n"
        "# RUN: %dxc_target -Fo %t.o %t/reject.hlsl\n"
        "# RUN: %offloader %t/pipeline.yaml %t.o\n"
    )
    (tests / "other.test").write_text(
        "# RUN: split-file %s %t\n"
        "# RUN: %dxc_target -Fo %t.o %t/source.hlsl\n"
        "# RUN: %offloader %t/pipeline.yaml %t.o\n"
    )
    (tests / "runtime-bad.test").write_text((tests / "other.test").read_text())
    (tests / "Inputs").mkdir()
    (tests / "Inputs/data.txt").write_text("test data")
    offloader = build / "install/bin/offloader"
    offloader.write_text(
        "#!/bin/sh\n"
        "[ -f \"$1\" ] || exit 9\n"
        "case \"$2\" in *runtime-bad.test*) exit 17;; esac\n"
        "[ \"$(cat \"$2\")\" = object ] || exit 8\n"
    )
    offloader.chmod(0o755)
    archive = tmp_path / "named.tar.gz"
    args = ("package", "repro", "Feature/good.test", "Feature/runtime-bad.test",
            "Feature/bad.yaml", "Feature/expected.test", "Feature/other.test",
            "--suite", "clang-vk",
            "--in", str(llvm), "--no-auto", "--out", str(archive))
    before = files(workspace)
    dry = cli(workspace, *args, "--dry-run")
    assert dry.returncode == 0, dry.stderr
    assert files(workspace) == before
    assert not archive.exists()
    result = cli(workspace, *args)
    assert result.returncode == 0, result.stderr
    target = tmp_path / "moved"
    unpack(archive, target)
    assert (target / "run.sh").exists() and (target / "run.cmd").exists()
    assert (target / "share/hlsl-test-suite/test/Feature/Inputs/data.txt").exists()
    assert not (target / "share/hlsl-test-suite/test/Feature/inside.test").exists()
    assert not (target / "bin/lit").exists()
    assert not (target / "bin/clang-dxc").exists()
    assert not (target / "share/hlsl-test-suite/lit").exists()
    assert not (target / "share/hlsl-test-suite/python").exists()
    assert "No target Python packages required" in (target / "requirements.txt").read_text()
    assert (target / "data/clang-vk/Feature/Output/good.test.tmp/source.hlsl").is_file()
    assert (target / "test/clang-vk/Feature/Output/good.test.tmp.o").read_text() == "object"
    assert json.loads((target / "commands.json").read_text())["Feature/bad.yaml"]["objects"]
    assert json.loads((target / "provenance.json").read_text())["target_python"] == "not required"
    # A missing target Python fails loudly if the generated runner invokes it.
    forbidden = tmp_path / "no-python"
    forbidden.mkdir()
    for name in ("python", "python3"):
        program = forbidden / name
        program.write_text("#!/bin/sh\necho PYTHON_USED >&2; exit 92\n")
        program.chmod(0o755)
    run_it = lambda: subprocess.run(
        ["/bin/sh", str(target / "run.sh")], cwd=tmp_path,
        capture_output=True, text=True,
        env={**os.environ, "PATH": str(forbidden) + ":/usr/bin:/bin"},
    )
    stale = target / "test/clang-vk/Feature/Output/good.test.tmp/stale.yaml"
    stale.write_text("previous invocation")
    completed = run_it()
    assert not stale.exists(), "split-file must restore pristine test data on every run"
    assert completed.returncode == 1, completed.stdout + completed.stderr
    assert "PASS: Feature/good.test" in completed.stdout
    assert "FAIL: Feature/runtime-bad.test" in completed.stdout
    assert "FAIL: Feature/bad.yaml" in completed.stdout
    assert "XFAIL: Feature/expected.test" in completed.stdout
    assert "PASS: Feature/other.test" in completed.stdout
    assert "PYTHON_USED" not in completed.stderr
    assert "call :test_4" in (target / "run.cmd").read_text()
    assert "exit /b %failed%" in (target / "run.cmd").read_text()
    (target / "test/clang-vk/Feature/Output/good.test.tmp.o").unlink()
    missing = run_it()
    assert "FAIL: Feature/good.test" in missing.stdout
    assert "PASS: Feature/other.test" in missing.stdout


def test_repro_refuses_uncompiled_named_tests(workspace, tmp_path):
    llvm, build, _ = precompiled_fixture(workspace)
    tests = build / "install/share/hlsl-test-suite/test/Feature"
    (tests / "pipe.test").write_text(
        "# RUN: split-file %s %t\n"
        "# RUN: %dxc_target -Fo %t.o %t/source.hlsl\n"
        "# RUN: %offloader %t/pipeline.yaml %t.o | FileCheck %s\n"
    )
    (tests / "conditional.test").write_text(
        "# REQUIRES: Vulkan\n# RUN: split-file %s %t\n"
        "# RUN: %dxc_target -Fo %t.o %t/source.hlsl\n"
        "# RUN: %offloader %t/pipeline.yaml %t.o\n"
    )
    archive = tmp_path / "named.tar.gz"
    archive.write_bytes(b"existing")
    for bad, reason in (("inside.test", "cannot precompile"),
                        ("only-runtime.test", "cannot precompile")):
        result = cli(workspace, "package", "repro", "Feature/good.test",
                     "Feature/" + bad, "--suite", "clang-vk", "--in", str(llvm),
                     "--no-auto", "--out", str(archive))
        assert result.returncode != 0, result.stdout + result.stderr
        assert reason in result.stderr
        assert archive.read_bytes() == b"existing"


def test_repro_falls_back_to_lit_for_all_named_tests(workspace, tmp_path):
    llvm, build, native = precompiled_fixture(workspace)
    lit_source = Path(__file__).resolve().parents[2] / "llvm-project/llvm/utils/lit/lit"
    lit_checkout = llvm / "llvm/utils/lit/lit"
    shutil.rmtree(lit_checkout)
    shutil.copytree(lit_source, lit_checkout,
                    ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
    installed = build / "install"
    tests = installed / "share/hlsl-test-suite/test"
    (tests / "lit.cfg.py").write_text(
        "import os\nimport lit.formats\n"
        "config.name = 'Repro-clang-vk'\n"
        "config.test_format = lit.formats.ShTest()\n"
        "config.suffixes = ['.test', '.yaml']\n"
        "config.excludes = ['Inputs', 'Output']\n"
        "config.available_features.add('Vulkan')\n"
        "config.test_source_root = os.path.dirname(__file__)\n"
        "config.test_exec_root = os.path.join(config.offloadtest_obj_root, 'test', 'clang-vk')\n"
        "config.substitutions.append(('%offloader', "
        "os.path.join(config.offloadtest_tools_dir, 'offloader')))\n"
        "config.substitutions.append(('split-file', "
        "os.path.join(config.llvm_tools_dir, 'split-file')))\n"
        "config.substitutions.append(('FileCheck', "
        "os.path.join(config.llvm_tools_dir, 'FileCheck')))\n"
    )
    offloader = installed / "bin/offloader"
    offloader.write_text("#!/bin/sh\nif [ -e \"$2\" ]; then cat \"$2\"; else exit 0; fi\n")
    offloader.chmod(0o755)
    checker = installed / "bin/FileCheck"
    checker.write_text("#!/bin/sh\ngrep -q '^object$'\n")
    checker.chmod(0o755)
    feature = tests / "Feature"
    (feature / "pipe.test").write_text(
        "# REQUIRES: Vulkan\n# RUN: split-file %s %t\n"
        "# RUN: %dxc_target -Fo %t.o %t/source.hlsl\n"
        "# RUN: %offloader %t/pipeline.yaml %t.o | FileCheck %s\n"
    )
    (feature / "negative.test").write_text(
        "# RUN: split-file %s %t\n"
        "# RUN: not %dxc_target -Fo %t.o %t/reject.hlsl\n"
        "# RUN: %offloader %t/pipeline.yaml %t.o\n"
    )
    (feature / "expected-bad.test").write_text(
        "# XFAIL: *\n# RUN: split-file %s %t\n"
        "# RUN: not %dxc_target -Fo %t.o %t/source.hlsl\n"
        "# RUN: %offloader %t/pipeline.yaml %t.o\n"
    )
    (feature / "nested-not.test").write_text(
        "# XFAIL: *\n# RUN: split-file %s %t\n"
        "# RUN: not not %dxc_target -Fo %t.o %t/reject.hlsl\n"
        "# RUN: %offloader %t/pipeline.yaml %t.o\n"
    )
    (feature / "bang.test").write_text(
        "# RUN: split-file %s %t\n"
        "# RUN: ! %dxc_target -Fo %t.o %t/reject.hlsl\n"
        "# RUN: %offloader %t/pipeline.yaml %t.o\n"
    )
    archive = tmp_path / "fallback.tar.gz"
    args = ("package", "repro", "Feature/good.test", "Feature/pipe.test",
            "Feature/negative.test", "Feature/expected-bad.test",
            "Feature/nested-not.test", "Feature/bang.test",
            "--suite", "clang-vk", "--in", str(llvm),
            "--no-auto", "--out", str(archive))
    before = files(workspace)
    dry = cli(workspace, *args, "--dry-run")
    assert dry.returncode == 0, dry.stderr
    assert "using lit/Python for ALL selected tests" in dry.stdout
    assert "Feature/pipe.test" in dry.stdout
    assert files(workspace) == before
    assert not archive.exists()
    result = cli(workspace, *args)
    assert result.returncode == 0, result.stderr
    assert "using lit/Python for ALL selected tests" in result.stdout
    target = tmp_path / "fallback-target"
    unpack(archive, target)
    assert "psutil" in (target / "requirements.txt").read_text()
    assert "pure-Python PyYAML are bundled" in (target / "requirements.txt").read_text()
    assert (target / "bin/lit").is_file()
    assert (target / "bin/precompiled-cc.py").is_file()
    assert not (target / "bin/clang-dxc").exists()
    assert not (target / "dxc").exists()
    assert "lit/Python" in json.loads((target / "provenance.json").read_text())["runner"]
    report = json.loads((target / "test/clang-vk/precompiled.json").read_text())
    negative = report["compiled"]["Feature/negative.test"][0]
    assert report["objects"][negative] == {"status": 7, "output": "validator rejected\n"}
    expected_bad = report["compiled"]["Feature/expected-bad.test"][0]
    assert report["objects"][expected_bad] == {"status": 0, "output": "compiled\n"}
    nested = report["compiled"]["Feature/nested-not.test"][0]
    assert report["objects"][nested] == {"status": 7, "output": "validator rejected\n"}
    bang = report["compiled"]["Feature/bang.test"][0]
    assert report["objects"][bang] == {"status": 7, "output": "validator rejected\n"}
    run_it = subprocess.run(["/bin/sh", str(target / "run.sh")], cwd=tmp_path,
                            capture_output=True, text=True,
                            env={**os.environ, "PYTHON": sys.executable,
                                 "PYTHONDONTWRITEBYTECODE": "1"})
    assert run_it.returncode == 0, run_it.stdout + run_it.stderr
    assert "PASS: Repro-clang-vk :: Feature/good.test" in run_it.stdout
    assert "PASS: Repro-clang-vk :: Feature/pipe.test" in run_it.stdout
    assert "PASS: Repro-clang-vk :: Feature/negative.test" in run_it.stdout
    assert "XFAIL: Repro-clang-vk :: Feature/expected-bad.test" in run_it.stdout
    assert "XFAIL: Repro-clang-vk :: Feature/nested-not.test" in run_it.stdout
    assert "PASS: Repro-clang-vk :: Feature/bang.test" in run_it.stdout
    assert "inside.test" not in run_it.stdout
    assert "bad.yaml" not in run_it.stdout


@pytest.mark.parametrize("command, reason", [
    ("not --crash %dxc_target -Fo %t.o %t/reject.hlsl",
     "unsupported compiler wrapper"),
    ("not env FOO=bar %dxc_target -Fo %t.o %t/reject.hlsl",
     "unsupported compiler wrapper"),
    ("not %dxc_target -Fo %t.o %t/reject.hlsl ; touch %t.bad",
     "RUN line requires a shell"),
])
def test_repro_rejects_unsafe_compile_wrappers(workspace, tmp_path, command, reason):
    llvm, build, _ = precompiled_fixture(workspace)
    tests = build / "install/share/hlsl-test-suite/test/Feature"
    (tests / "wrapped.test").write_text(
        "# RUN: split-file %s %t\n"
        f"# RUN: {command}\n"
        "# RUN: %offloader %t/pipeline.yaml %t.o\n"
    )
    archive = tmp_path / "wrapped.tar.gz"
    result = cli(workspace, "package", "repro", "Feature/good.test",
                 "Feature/wrapped.test", "--suite", "clang-vk", "--in", str(llvm),
                 "--no-auto", "--out", str(archive))
    assert result.returncode != 0
    assert "Feature/wrapped.test: cannot precompile" in result.stderr
    assert reason in result.stderr
    assert not archive.exists()


def test_repro_windows_fallback_is_unverified(workspace, tmp_path):
    llvm, build, _ = precompiled_fixture(workspace, "windows-x64")
    (build / "install/bin/split-file.exe").write_text("target split-file")
    tests = build / "install/share/hlsl-test-suite/test/Feature"
    (tests / "pipe.test").write_text(
        "# RUN: split-file %s %t\n"
        "# RUN: %dxc_target -Fo %t.o %t/source.hlsl\n"
        "# RUN: %offloader %t/pipeline.yaml %t.o | FileCheck %s\n"
    )
    archive = tmp_path / "fallback.zip"
    result = cli(workspace, "package", "repro", "Feature/good.test",
                 "Feature/pipe.test", "--suite", "clang-vk", "--in", str(llvm),
                 "--platform", "windows-x64", "--no-auto", "--out", str(archive))
    assert result.returncode == 0, result.stderr
    assert "using lit/Python" in result.stdout
    assert "Target execution unverified" not in result.stdout
    target = tmp_path / "windows-fallback"
    unpack(archive, target)
    assert (target / "bin/lit.cmd").is_file()
    assert "call \"%ROOT%bin\\lit.cmd\"" in (target / "run.cmd").read_text()
    assert "Target execution unverified (windows-x64)" in (target / "REPRO.md").read_text()
    assert "Python 3 is required" in (target / "requirements.txt").read_text()
    assert not (target / "bin/clang-dxc.exe").exists()
    assert not any(path.is_symlink() for path in target.rglob("*"))


def test_repro_windows_archives_cmd_runner_without_python(workspace, tmp_path):
    llvm, build, _ = precompiled_fixture(workspace, "windows-x64")
    bin_dir = build / "install/bin"
    (bin_dir / "offloader.exe").write_text("fake runtime")
    archive = tmp_path / "repro.zip"
    result = cli(workspace, "package", "repro", "Feature/good.test", "--suite",
                 "clang-vk", "--in", str(llvm), "--platform", "windows-x64",
                 "--no-auto", "--out", str(archive))
    assert result.returncode == 0, result.stderr
    target = tmp_path / "target"
    unpack(archive, target)
    cmd = (target / "run.cmd").read_text()
    assert '"%BIN%\\offloader.exe"' in cmd
    assert "call :test_0" in cmd
    assert (target / "run.sh").is_file()
    assert not (target / "bin/lit.cmd").exists()
    assert "Target execution unverified" not in result.stdout


def test_repro_xpass_and_duplicate_compile_are_not_hidden(workspace, tmp_path):
    llvm, build, _ = precompiled_fixture(workspace)
    tests = build / "install/share/hlsl-test-suite/test/Feature"
    (tests / "unexpected.test").write_text(
        "# XFAIL: *\n# RUN: split-file %s %t\n"
        "# RUN: %dxc_target -Fo %t.o %t/source.hlsl\n"
        "# RUN: %offloader %t/pipeline.yaml %t.o\n"
    )
    (tests / "duplicate.test").write_text(
        "# RUN: split-file %s %t\n"
        "# RUN: %dxc_target -Fo %t.o %t/source.hlsl\n"
        "# RUN: %dxc_target -Fo %t.o %t/reject.hlsl\n"
        "# RUN: %offloader %t/pipeline.yaml %t.o\n"
    )
    offloader = build / "install/bin/offloader"
    offloader.write_text("#!/bin/sh\nexit 0\n")
    offloader.chmod(0o755)
    archive = tmp_path / "repro.tar.gz"
    rejected = cli(workspace, "package", "repro", "Feature/duplicate.test",
                   "--suite", "clang-vk", "--in", str(llvm), "--no-auto",
                   "--out", str(archive), "--dry-run")
    assert rejected.returncode != 0
    assert "unique -Fo output" in rejected.stderr
    assert not archive.exists()
    result = cli(workspace, "package", "repro", "Feature/unexpected.test",
                 "--suite", "clang-vk", "--in", str(llvm), "--no-auto",
                 "--out", str(archive))
    assert result.returncode == 0, result.stderr
    target = tmp_path / "unpacked"
    unpack(archive, target)
    run_it = subprocess.run(["/bin/sh", str(target / "run.sh")],
                            capture_output=True, text=True)
    assert run_it.returncode == 1
    assert "XPASS: Feature/unexpected.test" in run_it.stdout


def test_repro_replays_multiple_runtime_commands_and_golden_data(workspace, tmp_path):
    llvm, build, _ = precompiled_fixture(workspace)
    tests = build / "install/share/hlsl-test-suite/test/Feature"
    (tests / "golden.test").write_text(
        "# RUN: split-file %s %t\n"
        "# RUN: %dxc_target -Fo %t.o %t/source.hlsl\n"
        "# RUN: %offloader %t/source.hlsl %t.o\n"
        "# RUN: imgdiff %goldenimage_dir/ref.png %t/source.hlsl\n"
    )
    site = build / "tools/OffloadTest/test/clang-vk/lit.site.cfg.py"
    site.write_text(site.read_text().replace(
        "import lit.llvm", "config.offloadtest_enable_debug = True\nimport lit.llvm"))
    offloader = build / "install/bin/offloader"
    offloader.write_text(
        "#!/bin/sh\n"
        "[ \"$1\" = -debug-layer ] && [ -f \"$2\" ] && [ -f \"$3\" ]\n"
    )
    offloader.chmod(0o755)
    imgdiff = build / "install/bin/imgdiff"
    imgdiff.write_text("#!/bin/sh\n[ -f \"$1\" ] && [ -f \"$2\" ]\n")
    imgdiff.chmod(0o755)
    archive = tmp_path / "golden.tar.gz"
    result = cli(workspace, "package", "repro", "Feature/golden.test",
                 "--in", str(llvm), "--no-auto", "--out", str(archive))
    assert result.returncode == 0, result.stderr
    target = tmp_path / "target"
    unpack(archive, target)
    run_it = subprocess.run(["/bin/sh", str(target / "run.sh")],
                            capture_output=True, text=True)
    assert run_it.returncode == 0, run_it.stdout + run_it.stderr
    assert "PASS: Feature/golden.test" in run_it.stdout
    assert (target / "share/hlsl-test-suite/golden-images/ref.png").is_file()
