"""Relocate configured offload lit sites without executing their Python code.

Only CMake's path(r"...") calls and the two known bare directory assignments
are rewritten. All remaining absolute string literals are rejected, including
paths introduced by a changed upstream template.
"""

import ast
import os
from pathlib import Path
import posixpath
import re
import tokenize
from io import StringIO

from .build_support import BuildError


_PATH = re.compile(r'\bpath\(r(["\'])(.*?)\1\)')
_BARE = re.compile(
    r'^(config\.(?:offloadtest_dxc_dir|goldenimage_dir)\s*=\s*)r(["\'])(.*?)\2\s*$',
    re.MULTILINE,
)
_WINDOWS = re.compile(r"^[A-Za-z]:[\\/]")


class LitRelocationError(BuildError):
    """The configured lit site cannot be run away from the build machine."""


def _absolute(value):
    # Also catch absolute paths embedded in compiler flags; a path that has
    # merely acquired '--some-option=' must not evade relocation validation.
    return (
        bool(re.search(r"(?:^|[\s=(])/(?!/)|(?:^|[\s=(])[A-Za-z]:[\\/]", value))
        or value.startswith("//") or value.startswith("\\\\")
    )


def _literal_paths(text):
    try:
        for token in tokenize.generate_tokens(StringIO(text).readline):
            if token.type == tokenize.STRING:
                value = ast.literal_eval(token.string)
                if isinstance(value, str) and _absolute(value):
                    yield value
            elif token.type == tokenize.COMMENT:
                value = token.string.lstrip("# ")
                if _absolute(value):
                    yield value
    except (SyntaxError, tokenize.TokenError, ValueError) as error:
        raise LitRelocationError(
            f"invalid generated lit configuration: {error}"
        ) from error


def relocate_lit(text, source, output, root, mappings):
    """Return a site config whose paths resolve from its destination after unpacking.

    The mapping keys are absolute build-machine prefixes and the values are
    relative package paths. A source path outside every prefix is an error;
    no output file is written until the complete configuration passes checks.
    """
    source = Path(source).resolve()
    output = Path(output).absolute()
    root = Path(root).absolute()
    try:
        relative_output = output.relative_to(root)
    except ValueError as error:
        raise LitRelocationError(f"{output}: lit site must be inside {root}") from error
    if relative_output == Path("."):
        raise LitRelocationError("lit site must be a file below the package root")
    entries = []
    for prefix, destination in mappings.items():
        prefix = Path(prefix).resolve()
        destination = Path(destination)
        if destination.is_absolute() or ".." in destination.parts:
            raise LitRelocationError(
                f"invalid package mapping destination: {destination}"
            )
        entries.append((prefix, destination))
    # A suite's obj root is above test/<suite> in both LLVM and standalone layouts.
    entries.append((source.parent.parent.parent, Path(".")))
    entries.sort(key=lambda item: len(item[0].parts), reverse=True)
    relative_root = os.path.relpath(root, output.parent).replace(os.sep, "/")

    def map_path(value):
        if not value:
            return value
        original = Path(value)
        if not original.is_absolute() and not _WINDOWS.match(value):
            original = source.parent / original
        # Preserve a symlink's final name (e.g. dxc -> dxc-3.7) when mapped.
        named = original.parent.resolve() / original.name
        for candidate in (named, original.resolve()):
            for prefix, destination in entries:
                try:
                    remainder = candidate.relative_to(prefix)
                except ValueError:
                    continue
                return posixpath.normpath(posixpath.join(
                    relative_root, destination.as_posix(), remainder.as_posix()
                ))
        raise LitRelocationError(f"{source}: unmapped build-machine path {value!r}")

    # LLVM's generated header names the source template with a host absolute
    # path. It is a comment, not a runtime setting, so remove it explicitly.
    text = re.sub(r"(?m)^# Autogenerated from [^\n]*\n", "", text)
    body = _PATH.sub(lambda match: f'path(r"{map_path(match.group(2))}")', text)
    body = _BARE.sub(
        lambda match: f'{match.group(1)}path(r"{map_path(match.group(3))}")',
        body,
    )
    survivors = sorted(set(_literal_paths(body)))
    if survivors:
        raise LitRelocationError(
            f"{source}: absolute paths survive relocation: {', '.join(survivors)}"
        )
    anchor = "\nimport lit.llvm\n"
    if anchor not in body:
        raise LitRelocationError(
            f"{source}: generated lit site lacks the expected lit.llvm anchor"
        )
    # The suite consumes DXC locations while load_config runs. Apply target
    # overrides before that call, not after it has already loaded lit.cfg.py.
    body = body.replace(anchor, (
        '\n# DXC ships in a separate archive, selected on the target.\n'
        '_hlsl_dxc = _hlsl_os.environ.get("HLSL_DXC_DIR")\n'
        'if _hlsl_dxc:\n'
        '    config.offloadtest_dxc_dir = _hlsl_dxc\n'
        '    config.offloadtest_dxc = "\\\"" + _hlsl_os.path.join(_hlsl_dxc, '
        '"dxc.exe" if config.offloadtest_os == "Windows" else "dxc") + "\\\""\n'
    ) + anchor, 1)
    # os.path.abspath(__file__) is evaluated on the target; no host path enters.
    return (
        "# Relocated from a configured offload suite by hlsl package full.\n"
        "# All site paths are relative to this file; keep it inside the archive.\n"
        "import os as _hlsl_os\nimport sys as _hlsl_sys\n"
        f'_hlsl_pkg = _hlsl_os.path.abspath(_hlsl_os.path.join('
        f'_hlsl_os.path.dirname(__file__), {relative_root!r}))\n'
        '_hlsl_deps = _hlsl_os.path.join(\n'
        '    _hlsl_pkg, "share", "hlsl-test-suite", "python")\n'
        'if _hlsl_deps not in _hlsl_sys.path:\n    _hlsl_sys.path.append(_hlsl_deps)\n'
        '# Lit 18+ makes the global timeout read-only; the suite still writes it.\n'
        'import lit.LitConfig as _hlsl_lit_config\n'
        'if isinstance(getattr(_hlsl_lit_config.LitConfig,\n'
        '                      "maxIndividualTestTime", None), property):\n'
        '    _hlsl_lit_config.LitConfig.maxIndividualTestTime = property(\n'
        '        lambda self: self._maxIndividualTestTime, lambda self, value: None)\n'
        + body
        + '\n# Keep the suite timeout even if the old lit global setter was ignored.\n'
        'try:\n    import psutil as _hlsl_psutil\n'
        'except ImportError:\n'
        '    config.maxIndividualTestTime = 0\n'
        '    lit_config.note("psutil not installed: per-test timeout disabled")\n'
        'else:\n'
        '    if lit_config.maxIndividualTestTime is None:\n'
        '        config.maxIndividualTestTime = 300\n'
    )
